name: TypeScript Checker Declaration

# This action works with pull requests and pushes
on: [push, pull_request]

jobs:
  typing:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.25.1
          run_install: false

      - name: Install depends
        run: pnpm i --no-frozen-lockfile

      - name: Typing
        run: pnpm build && cd preview && pnpm i && cd .. && pnpm typing
